### ISSUE TITLE
openebs-lvm-plugin is busylooping on systems without dm-snapshot kernel module loaded

### ISSUE THREAD

**Issue by flokli** [openebs/lvm-localpv#163]
**What steps did you take and what happened:**

I tried to snapshot a volume created by lvm-localpv.

I created a [Default SnapshotClass Without SnapSize Parameter](https://github.com/openebs/lvm-localpv/blob/51707f7f3fa4ab643feabde7a459743bfc70b33e/docs/snapshot.md#default-snapshotclass-without-snapsize-parameter), and then a `VolumeSnapshot` resource:

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: lvm-localpv-snap
spec:
  volumeSnapshotClassName: lvmpv-snapclass
  source:
    persistentVolumeClaimName: datadir-redpanda-0
```

**What did you expect to happen:**
Snapshot to be created.

* `kubectl logs -f openebs-lvm-controller-0 -n kube-system -c openebs-lvm-plugin`

```
I1017 09:26:48.057768       1 grpc.go:72] GRPC call: /csi.v1.Controller/CreateSnapshot requests {"name":"snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8","source_volume_id":"pvc-d293d56b-45da-412d-ab62-fec20652e71b"}
I1017 09:26:48.057937       1 controller.go:572] CreateSnapshot volume snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8 for pvc-d293d56b-45da-412d-ab62-fec20652e71b
I1017 09:26:48.068293       1 grpc.go:81] GRPC response: {"snapshot":{"creation_time":{"seconds":1634462808},"snapshot_id":"pvc-d293d56b-45da-412d-ab62-fec20652e71b@snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8","source_volume_id":"pvc-d293d56b-45da-412d-ab62-fec20652e71b"}}
I1017 09:26:48.650574       1 grpc.go:72] GRPC call: /csi.v1.Identity/GetPluginInfo requests {}
I1017 09:26:48.650691       1 grpc.go:81] GRPC response: {"name":"local.csi.openebs.io","vendor_version":"0.8.2"}
I1017 09:26:48.651376       1 grpc.go:72] GRPC call: /csi.v1.Controller/CreateSnapshot requests {"name":"snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8","source_volume_id":"pvc-d293d56b-45da-412d-ab62-fec20652e71b"}
I1017 09:26:48.651521       1 controller.go:572] CreateSnapshot volume snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8 for pvc-d293d56b-45da-412d-ab62-fec20652e71b
I1017 09:26:48.657290       1 grpc.go:81] GRPC response: {"snapshot":{"creation_time":{"seconds":1634462808},"snapshot_id":"pvc-d293d56b-45da-412d-ab62-fec20652e71b@snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8","source_volume_id":"pvc-d293d56b-45da-412d-ab62-fec20652e71b"}}
I1017 09:26:49.258316       1 grpc.go:72] GRPC call: /csi.v1.Identity/GetPluginInfo requests {}
I1017 09:26:49.258430       1 grpc.go:81] GRPC response: {"name":"local.csi.openebs.io","vendor_version":"0.8.2"}
I1017 09:26:49.259088       1 grpc.go:72] GRPC call: /csi.v1.Controller/CreateSnapshot requests {"name":"snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8","source_volume_id":"pvc-d293d56b-45da-412d-ab62-fec20652e71b"}
I1017 09:26:49.259214       1 controller.go:572] CreateSnapshot volume snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8 for pvc-d293d56b-45da-412d-ab62-fec20652e71b
I1017 09:26:49.274993       1 grpc.go:81] GRPC response: {"snapshot":{"creation_time":{"seconds":1634462809},"snapshot_id":"pvc-d293d56b-45da-412d-ab62-fec20652e71b@snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8","source_volume_id":"pvc-d293d56b-45da-412d-ab62-fec20652e71b"}}
I1017 09:26:49.857480       1 grpc.go:72] GRPC call: /csi.v1.Identity/GetPluginInfo requests {}
I1017 09:26:49.857635       1 grpc.go:81] GRPC response: {"name":"local.csi.openebs.io","vendor_version":"0.8.2"}
I1017 09:26:49.858364       1 grpc.go:72] GRPC call: /csi.v1.Controller/CreateSnapshot requests {"name":"snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8","source_volume_id":"pvc-d293d56b-45da-412d-ab62-fec20652e71b"}
I1017 09:26:49.858548       1 controller.go:572] CreateSnapshot volume snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8 for pvc-d293d56b-45da-412d-ab62-fec20652e71b
I1017 09:26:49.874360       1 grpc.go:81] GRPC response: {"snapshot":{"creation_time":{"seconds":1634462809},"snapshot_id":"pvc-d293d56b-45da-412d-ab62-fec20652e71b@snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8","source_volume_id":"pvc-d293d56b-45da-412d-ab62-fec20652e71b"}}
I1017 09:26:50.450447       1 grpc.go:72] GRPC call: /csi.v1.Identity/GetPluginInfo requests {}
I1017 09:26:50.450576       1 grpc.go:81] GRPC response: {"name":"local.csi.openebs.io","vendor_version":"0.8.2"}
I1017 09:26:50.451314       1 grpc.go:72] GRPC call: /csi.v1.Controller/CreateSnapshot requests {"name":"snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8","source_volume_id":"pvc-d293d56b-45da-412d-ab62-fec20652e71b"}
I1017 09:26:50.451583       1 controller.go:572] CreateSnapshot volume snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8 for pvc-d293d56b-45da-412d-ab62-fec20652e71b
I1017 09:26:50.456889       1 grpc.go:81] GRPC response: {"snapshot":{"creation_time":{"seconds":1634462810},"snapshot_id":"pvc-d293d56b-45da-412d-ab62-fec20652e71b@snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8","source_volume_id":"pvc-d293d56b-45da-412d-ab62-fec20652e71b"}}
 ```
* `kubectl logs -f openebs-lvm-node-[xxxx] -n kube-system -c openebs-lvm-plugin`
```
E1017 09:19:28.198591       1 snapshot.go:242] error syncing 'openebs/snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8': exit status 3, requeuing
E1017 09:19:48.682737       1 lvm_util.go:501] lvm: could not create snapshot lvmvg/ccd9b76d-b16f-4a17-9809-0f769c0bc2f8 cmd [--snapshot --name ccd9b76d-b16f-4a17-9809-0f769c0bc2f8 --permission r /dev/lvmvg/pvc-d293d56b-45da-412d-ab62-fec20652e71b --size 107374182400b] error: modprobe: can't change directory to '/lib/modules': No such file or directory
  /sbin/modprobe failed: 1
  snapshot: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
E1017 09:19:48.682764       1 snapshot.go:242] error syncing 'openebs/snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8': exit status 3, requeuing
I1017 09:20:26.774560       1 lvmnode.go:274] Successfully synced 'openebs/redpanda-2'
E1017 09:20:29.646872       1 lvm_util.go:501] lvm: could not create snapshot lvmvg/ccd9b76d-b16f-4a17-9809-0f769c0bc2f8 cmd [--snapshot --name ccd9b76d-b16f-4a17-9809-0f769c0bc2f8 --permission r /dev/lvmvg/pvc-d293d56b-45da-412d-ab62-fec20652e71b --size 107374182400b] error: modprobe: can't change directory to '/lib/modules': No such file or directory
  /sbin/modprobe failed: 1
  snapshot: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
E1017 09:20:29.646928       1 snapshot.go:242] error syncing 'openebs/snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8': exit status 3, requeuing
I1017 09:21:26.746526       1 lvmnode.go:274] Successfully synced 'openebs/redpanda-2'
E1017 09:21:51.571130       1 lvm_util.go:501] lvm: could not create snapshot lvmvg/ccd9b76d-b16f-4a17-9809-0f769c0bc2f8 cmd [--snapshot --name ccd9b76d-b16f-4a17-9809-0f769c0bc2f8 --permission r /dev/lvmvg/pvc-d293d56b-45da-412d-ab62-fec20652e71b --size 107374182400b] error: modprobe: can't change directory to '/lib/modules': No such file or directory
  /sbin/modprobe failed: 1
  snapshot: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
E1017 09:21:51.571168       1 snapshot.go:242] error syncing 'openebs/snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8': exit status 3, requeuing
I1017 09:22:26.766557       1 lvmnode.go:274] Successfully synced 'openebs/redpanda-2'
I1017 09:23:26.746535       1 lvmnode.go:274] Successfully synced 'openebs/redpanda-2'
I1017 09:24:26.762518       1 lvmnode.go:274] Successfully synced 'openebs/redpanda-2'
E1017 09:24:35.415262       1 lvm_util.go:501] lvm: could not create snapshot lvmvg/ccd9b76d-b16f-4a17-9809-0f769c0bc2f8 cmd [--snapshot --name ccd9b76d-b16f-4a17-9809-0f769c0bc2f8 --permission r /dev/lvmvg/pvc-d293d56b-45da-412d-ab62-fec20652e71b --size 107374182400b] error: modprobe: can't change directory to '/lib/modules': No such file or directory
  /sbin/modprobe failed: 1
  snapshot: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
E1017 09:24:35.415304       1 snapshot.go:242] error syncing 'openebs/snapshot-ccd9b76d-b16f-4a17-9809-0f769c0bc2f8': exit status 3, requeuing
I1017 09:25:26.754542       1 lvmnode.go:274] Successfully synced 'openebs/redpanda-2'
I1017 09:26:26.770526       1 lvmnode.go:274] Successfully synced 'openebs/redpanda-2'
I1017 09:27:26.778556       1 lvmnode.go:274] Successfully synced 'openebs/redpanda-2'
```
* `kubectl get pods -n kube-system`
```
NAME                                           READY   STATUS    RESTARTS   AGE
metrics-server-86cbb8457f-sgxtn                1/1     Running   0          31d
local-path-provisioner-5ff76fc89d-h5hr5        1/1     Running   0          31d
kube-vip-ds-cp-hmkdq                           1/1     Running   0          31d
coredns-7448499f4d-6f76n                       1/1     Running   0          31d
kube-vip-ds-svc-l4ncf                          1/1     Running   0          3d
kube-vip-ds-svc-qqtlj                          1/1     Running   0          3d
kube-vip-ds-svc-vlpcs                          1/1     Running   0          3d
kube-vip-ds-svc-szsb4                          1/1     Running   0          3d
openebs-lvm-node-v8wpt                         2/2     Running   0          3d
openebs-lvm-node-v8f6s                         2/2     Running   0          3d
openebs-lvm-controller-0                       5/5     Running   0          3d
openebs-lvm-node-rjtgl                         2/2     Running   0          3d
kube-state-metrics-5f97897c99-b45mq            1/1     Running   0          3d
openebs-lvm-node-5rh8l                         2/2     Running   0          3d
kube-vip-ds-svc-kchn4                          1/1     Running   0          3d
openebs-lvm-node-2jtn9                         2/2     Running   0          3d
kube-vip-ds-svc-wp597                          1/1     Running   0          3d
kube-vip-ds-svc-2qv26                          1/1     Running   0          3d
openebs-lvm-node-2gb2m                         2/2     Running   0          3d
openebs-lvm-node-mc5rj                         2/2     Running   0          3d
cloud-provider-equinix-metal-7fb9654c9-2xzxc   1/1     Running   2          31d
```
* `kubectl get lvmvol -A -o yaml`
```
apiVersion: v1
items:
- apiVersion: local.openebs.io/v1alpha1
  kind: LVMVolume
  metadata:
    creationTimestamp: "2021-10-14T09:48:54Z"
    finalizers:
    - lvm.openebs.io/finalizer
    generation: 3
    labels:
      kubernetes.io/nodename: redpanda-2
    name: pvc-d293d56b-45da-412d-ab62-fec20652e71b
    namespace: openebs
    resourceVersion: "10188280"
    uid: 0f25c600-c69e-459e-8274-b7ed70081f0b
  spec:
    capacity: "107374182400"
    ownerNodeID: redpanda-2
    shared: "no"
    thinProvision: "no"
    vgPattern: ^lvmvg$
    volGroup: lvmvg
  status:
    state: Ready
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Anything else you would like to add:**

 - The `openebs-lvm-controller` pod is busylooping a lot. It probably shouldn't try multiple times per second
 - The logs of the `openebs-lvm-node` suggest there might be a problem with some missing kernel module:
   `lvm_util.go:501] lvm: could not create snapshot lvmvg/ccd9b76d-b16f-4a17-9809-0f769c0bc2f8 cmd [--snapshot --name ccd9b76d-b16f-4a17-9809-0f769c0bc2f8 --permission r /dev/lvmvg/pvc-d293d56b-45da-412d-ab62-fec20652e71b --size 107374182400b] error: modprobe: can't change directory to '/lib/modules': No such file or directory`
  Maybe this folder doesn't exist in the pod/It doesn't exist on the host/It's not mounted into the pod/We need to have another kernel module around on the host?

If it's some missing kernel feature, this might just need a bit more documentation and some more graceful error handling.

**Environment:**
- LVM Driver version: 0.8.2
- Kubernetes version (use `kubectl version`): v1.21.2+k3s1
- Kubernetes installer & version: k3s
- Cloud provider or hardware configuration: Equinix Metal
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS

**Comment by flokli** [comment]
From a bit of research, during snapshotting we invoke the `lvcreate` command, which does try to invoke modprobe to load the `dm_snapshot` kernel module (as it's not yet loaded).

Maybe we need to mount the host kernel modules from inside the pod? Or document that this kernel module needs to be loaded in each hosts' distro configuration before deploying lvm-localpath?

**Comment by flokli** [comment]
I manually ran a `modprobe dm-snapshot` on the host, and the volumesnapshotcontent got "ReadyToUse".

**Comment by pawanpraka1** [comment]
@flokli that is the prerequisite for the snapshot. We need add that in our doc (if not mentioned) https://github.com/openebs/lvm-localpv/blob/develop/docs/snapshot.md.

**Comment by flokli** [comment]
Yeah, it's not documented right now, and the error handling isn't very graceful - we shouldn't try multiple times per second.

**Comment by pawanpraka1** [comment]
fixed via https://github.com/openebs/lvm-localpv/pull/166

**Comment by flokli** [comment]
This issue is about the non-graceful busylooping, which isn't fixed yet.

**Comment by pawanpraka1** [comment]
@flokli that is as per design, the driver will keep on trying to create snapshot/volume. That is the LVM-LocalPV reconcillation logic.

**Comment by flokli** [comment]
Yes, but it should backoff on failure. There's no point trying multiple times per second.

**Comment by pawanpraka1** [comment]
@flokli hmmm make sense to add backoff here. have reopened it. I will add this to our roadmap.

**Comment by flokli** [comment]
Thanks!

**Comment by abhilashshetty04** [comment]
Hi @flokli . Fixed via https://github.com/openebs/lvm-localpv/pull/186

Please refer following commit:
https://github.com/openebs/lvm-localpv/pull/186/commits/285c4fdf884fe8e22d8bd5ba7d575dc84aa21916#diff-15287c675d6a896a857d384251c95d7ecbf7b84f01d6629bd89e588c17ba330eR93

**Comment by flokli** [comment]
Thanks!
